
// Objective-C API for talking to the following Go packages
//
//	torrserverkit
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TorrServerKit_FRAMEWORK_H__
#define __TorrServerKit_FRAMEWORK_H__

#include "Torrserverkit.objc.h"
#include "Universe.objc.h"

#endif
