// Objective-C API for talking to torrserverkit Go package.
//   gobind -lang=objc torrserverkit
//
// File is generated by gobind. Do not edit.

#ifndef __Torrserverkit_H__
#define __Torrserverkit_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * IsRunning returns true if TorrServer is actively running.
 */
FOUNDATION_EXPORT BOOL TorrserverkitIsRunning(void);

/**
 * StartServer starts the embedded TorrServer HTTP engine and BitTorrent client.
Returns an empty string on success, or an error message on failure.
 */
FOUNDATION_EXPORT NSString* _Nonnull TorrserverkitStartServer(long port, NSString* _Nullable dataDir);

/**
 * StopServer stops the running TorrServer instance.
Returns an empty string on success, or an error message on failure.
 */
FOUNDATION_EXPORT NSString* _Nonnull TorrserverkitStopServer(void);

#endif
